# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamClassic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('two_fgm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
