# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamclassic',
            name='three_fgm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teamclassic',
            name='three_fgms',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teamclassic',
            name='three_prtg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teamclassic',
            name='two_fgms',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teamclassic',
            name='two_prtg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='teamclassic',
            name='two_fgm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
