# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180319_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamclassic',
            old_name='fta',
            new_name='ftms',
        ),
    ]
