# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180319_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRebPct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('ors_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ors_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ors_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orb_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orb_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orb_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orf_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orf_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orf_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drs_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drs_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drs_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drb_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drb_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drb_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drf_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drf_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drf_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ort_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ort_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ort_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drt_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drt_a', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drt_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
