# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teamrebpct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamRebPct',
            new_name='TeamTeamRebPct',
        ),
    ]
