# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_teamteampct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTeamShotDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('zero_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
