# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_teamteamshotadv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamteamshotadv',
            old_name='ast_prtg',
            new_name='avg_dist',
        ),
        migrations.RenameField(
            model_name='teamteamshotadv',
            old_name='blk_prtg',
            new_name='efg_prtg',
        ),
        migrations.RenameField(
            model_name='teamteamshotadv',
            old_name='fls_prtg',
            new_name='pps',
        ),
        migrations.RenameField(
            model_name='teamteamshotadv',
            old_name='stl_prtg',
            new_name='ts_prtg',
        ),
        migrations.RenameField(
            model_name='teamteamshotadv',
            old_name='tov_prtg',
            new_name='usg_prtg',
        ),
    ]
