# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20180418_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('at_home', models.IntegerField()),
                ('team_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('team_poss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('off_rtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('oppo_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('oppo_poss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('def_rtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_rtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
