# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='TeamSummary',
        ),
    ]
