# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20180422_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsummary',
            name='win_prtg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
