# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClassic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('two_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('two_fgms', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('two_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fgms', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ftm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ftms', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ft_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('off_reb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('def_reb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tot_reb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('blk', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('to', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fls', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mi', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
