# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerteamrebpct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamPct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('ast_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stl_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('blk_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tov_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fls_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamShotAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('efg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ts_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('usg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_dist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamShotDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('zero_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zero_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eight_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sixteen_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fgm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_fg_prtg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_fga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_ast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('three_prtg_pts', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
